export const routeNames = {
  loginRoute: 'loginRoute',
  homeRoute: 'homeRoute',
  onbaordingRouteOne: 'onbaordingRouteOne',
  onbaordingRouteTwo: 'onbaordingRouteTwo',
  alertHistory: 'alertHistory',
  markAttendance: 'Mark Attendance',
  newPage: 'newPage',
  detectionHistory: 'DetectionHistory',
  dailySummaryReport: 'DailySummaryReport',
  dailyFallSummaryReport: 'DailyFallSummaryReport',
  emotionSummaryReport: 'EmotionSummaryReport',
  rangeDetectionReport: 'RangeDetectionReport',
  reportNavigationPage: 'ReportNavigationPage',
};
